# Generated by Django 3.0.5 on 2021-04-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=1000)),
                ('cost', models.CharField(max_length=1000)),
            ],
        ),
    ]
